/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.LLamadas;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aolivero11
 */
public class Agrega extends javax.swing.JDialog {

    /**
     * Creates new form Agrega
     */
    String ruta;
    ObjectOutputStream salida;
    ArrayList<LLamadas> llamadas;

    public Agrega(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ruta = "src/datos/llamadas.txt";
        try {
            llamadas = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, llamadas);
        Helper.llenarTabla(tblTablaPrincipal, ruta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOperador = new javax.swing.JTextField();
        txtCMinutos = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOperador1 = new javax.swing.JTextField();
        txtCMinutos1 = new javax.swing.JTextField();
        txtValor1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cmdGuardar1 = new javax.swing.JButton();
        cmdEliminar1 = new javax.swing.JButton();
        cmdLimpiar1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOperador2 = new javax.swing.JTextField();
        txtCMinutos2 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        cmdGuardar2 = new javax.swing.JButton();
        cmdEliminar2 = new javax.swing.JButton();
        cmdLimpiar2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTablaPrincipal = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos principales:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Operador:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad de minutos:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Valor de la llamada:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));
        jPanel2.add(txtOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 30));

        txtCMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMinutosActionPerformed(evt);
            }
        });
        jPanel2.add(txtCMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 30));
        jPanel2.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, 190));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones\n", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        cmdEliminar.setText("Eliminar");
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        cmdLimpiar.setText("Limpiar");
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 140, 190));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Llamadas:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Operador", "Cantidad de minutos", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, 240));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 510, 280));

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos principales:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Operador:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad de minutos:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Valor de la llamada:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));
        jPanel6.add(txtOperador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 30));

        txtCMinutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMinutos1ActionPerformed(evt);
            }
        });
        jPanel6.add(txtCMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 30));
        jPanel6.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 110, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, 190));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones\n", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar1.setText("Guardar");
        cmdGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardar1ActionPerformed(evt);
            }
        });
        jPanel7.add(cmdGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        cmdEliminar1.setText("Eliminar");
        jPanel7.add(cmdEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        cmdLimpiar1.setText("Limpiar");
        jPanel7.add(cmdLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 140, 190));

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Llamadas:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Operador", "Cantidad de minutos", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, 240));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 510, 280));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 4));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos principales:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Operador:");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad de minutos:");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Valor de la llamada:");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));
        jPanel10.add(txtOperador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 30));

        txtCMinutos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMinutos2ActionPerformed(evt);
            }
        });
        jPanel10.add(txtCMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 30));
        jPanel10.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 110, 30));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, 190));

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones\n", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar2.setText("Guardar");
        cmdGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardar2ActionPerformed(evt);
            }
        });
        jPanel11.add(cmdGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        cmdEliminar2.setText("Eliminar");
        cmdEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminar2ActionPerformed(evt);
            }
        });
        jPanel11.add(cmdEliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        cmdLimpiar2.setText("Limpiar");
        cmdLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiar2ActionPerformed(evt);
            }
        });
        jPanel11.add(cmdLimpiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 140, 190));

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Llamadas:", 0, 0, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTablaPrincipal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tblTablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Operador", "Cantidad de minutos", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTablaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaPrincipalMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTablaPrincipal);

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, 240));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 510, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(689, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMinutosActionPerformed

    }//GEN-LAST:event_txtCMinutosActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed

    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void txtCMinutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMinutos1ActionPerformed

    }//GEN-LAST:event_txtCMinutos1ActionPerformed

    private void cmdGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardar1ActionPerformed

    }//GEN-LAST:event_cmdGuardar1ActionPerformed

    private void txtCMinutos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMinutos2ActionPerformed

    }//GEN-LAST:event_txtCMinutos2ActionPerformed

    private void cmdGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardar2ActionPerformed
        String operador, cantm, valor;

        operador = txtOperador2.getText();
        cantm = txtCMinutos2.getText();
        valor = txtValor2.getText();

        LLamadas l = new LLamadas(operador, cantm, valor);
        try {
            l.guardar(salida);
        } catch (IOException ex) {
            Logger.getLogger(Agrega.class.getName()).log(Level.SEVERE, null, ex);
        }
        Helper.llenarTabla(tblTablaPrincipal, ruta);

        txtOperador2.setText("");
        txtCMinutos2.setText("");
        txtValor2.setText("");
        txtOperador2.requestFocusInWindow();

    }//GEN-LAST:event_cmdGuardar2ActionPerformed

    private void cmdEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminar2ActionPerformed
        int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar esta llamada?", "Eliminar", JOptionPane.YES_NO_OPTION);

        ArrayList<LLamadas> llamadas = Helper.traerDatos(ruta);
        if (op == JOptionPane.YES_OPTION) {
            i = tblTablaPrincipal.getSelectedRow();
            llamadas.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Agrega.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Agrega.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, llamadas);
            Helper.llenarTabla(tblTablaPrincipal, ruta);
            txtOperador2.setText("");
            txtCMinutos2.setText("");
            txtValor2.setText("");
            txtOperador2.requestFocusInWindow();
        }
    }//GEN-LAST:event_cmdEliminar2ActionPerformed

    private void cmdLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiar2ActionPerformed
        txtOperador2.setText("");
        txtCMinutos2.setText("");
        txtValor2.setText("");
        txtOperador2.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiar2ActionPerformed

    private void tblTablaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaPrincipalMouseClicked
        int i;
        LLamadas l;
        ArrayList<LLamadas> personas = Helper.traerDatos(ruta);
        i = tblTablaPrincipal.getSelectedRow();
        
        l = personas.get(i);

        txtOperador2.setText(l.getOperador());
        txtCMinutos2.setText(l.getCantidadm());
        txtValor2.setText(l.getValor());
    }//GEN-LAST:event_tblTablaPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agrega dialog = new Agrega(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdEliminar1;
    private javax.swing.JButton cmdEliminar2;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdGuardar1;
    private javax.swing.JButton cmdGuardar2;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLimpiar1;
    private javax.swing.JButton cmdLimpiar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tblTablaPrincipal;
    private javax.swing.JTextField txtCMinutos;
    private javax.swing.JTextField txtCMinutos1;
    private javax.swing.JTextField txtCMinutos2;
    private javax.swing.JTextField txtOperador;
    private javax.swing.JTextField txtOperador1;
    private javax.swing.JTextField txtOperador2;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
